sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '14'
script:
  - yarn install
  - yarn lint
  - yarn test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
